services:
  db:
    image: postgis/postgis:17-3.5
    container_name: dc-postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: dc
      POSTGRES_PASSWORD: dc
      POSTGRES_DB: dc
      TZ: Asia/Bangkok
    ports:
      - "5436:5432"
    volumes:
      - dc-pgdata:/var/lib/postgresql/data
      - ./db:/db:ro

volumes:
  dc-pgdata:
